inherit_from: .rubocop_todo.yml

require: 
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config/deploy.rb'
    - 'config/initializers/blacklight_url_helper_behavior.rb'
    - 'config/environments/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 374 # todo really should be 120
  Exclude:
    - 'config/initializers/devise.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/requests/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4
  Exclude:
    - 'spec/views/**/*'
    - 'spec/features/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/models/resource.rb'
    - 'app/models/study.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/dss.rake'
    - 'app/controllers/catalog_controller.rb'

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'lib/tasks/dss.rake'
