version: 2.1
orbs: 
  browser-tools: circleci/browser-tools@1.4.8
  node: circleci/node@5.0.3
jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>-browsers
        environment:
          SOLR_URL: localhost
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: dss
      - image: solr:8-alpine
        command: bin/solr -cloud -noprompt -f -p 8888
      - image: postgres:13-alpine
        environment:
          POSTGRES_USER: dss
          POSTGRES_DB: dss_test
          POSTGRES_HOST_AUTH_METHOD: trust

    working_directory: ~/DSS
    steps: &build_steps
      - checkout
      #set timezone to est
      - run:
          name: Set Timezone to EST
          command: echo 'America/New_York' = /etc/timezone
      # Install Bundler
      - run: gem install bundler -v '~> 2.0'
      # Restore bundle cache
      - restore_cache:
          keys:
          - v1-DSS-{{ checksum "Gemfile.lock" }}
          - v1-DSS-
      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install other dependencies 
          command: |
            sudo apt install postgresql-client
      - save_cache:
          key: v1-DSS-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - node/install:
          install-yarn: true
          node-version: '20.11.1'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Load config into solr
          command: |
            cd solr/config
            zip -1 -r solr_config.zip ./*
            curl -H "Content-type:application/octet-stream" --data-binary @solr_config.zip "http://localhost:8888/solr/admin/configs?action=UPLOAD&name=dss-core-test"
            curl -H 'Content-type: application/json' http://localhost:8888/api/collections/ -d '{create: {name: dss-core-test, config: dss-core-test, numShards: 1}}'
      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - run:
          name: Database setup
          command: bundle exec rake db:setup
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Run Rspec
          command: bundle exec rspec
  bearer:
    docker:
      - image: cimg/ruby:3.2
    environment:
      # Set to default branch of your repo
      DEFAULT_BRANCH: main
    steps:
      - checkout
      - run: curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh -s -- -b /tmp
      - run: CURRENT_BRANCH=$CIRCLE_BRANCH SHA=$CIRCLE_SHA1 /tmp/bearer scan .
  semgrep:
    docker:
        - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: Check code against community-provided and custom semgrep rules
          command: semgrep ci --config auto
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["3.1.3"]
      - bearer
      - semgrep
